jigintern/SAWAYAKA-COMMUNICATION

- public/daily_result/index.html
- public/daily_result/style.css
daily_resultページ内にindex.html, style.cssを作成した
#3
> ✨ daily_resultページの追加

- public/components/footer.html
- public/components/header.html
- public/daily_result/index.html
- public/submit_post/index.html
> ✨　submit_postページの作成

- public/styles/components.css
- public/styles/submit_post.css
- public/submit_post/index.html
- CSSの送信フォームのCSS設計
- 全ページのmain CSSの調整
#11 
https://sawa-communication-sve3d2b2mkag.deno.dev/
> 👍 SP 送信フォーム CSS調整(全体含む)

- deno.json
- library/post_add_db_sp.js
- library/post_delete_db_sp.js
- library/post_getall_db_sp.js
- public/index.html
- server.deno.js
> SPの追加、削除、全件取得の実装

- library/post_add_db_sp.js
- library/post_delete_db_sp.js
- library/post_getall_db_sp.js
- public/index.html
- public/submit_post/submitting.js
誰がSPを投稿するのかを設定できるようになりました。また、URLを.envから取得可能になっています。
> SPをだれが投稿するのか設定できるようにした

- public/components/up_leaf.html
- public/submit_post/index.html
- public/submit_post/submitting.js
SP送信時に演出が発生するように
#25 
https://sawa-communication-2tgaz2tbqtn4.deno.dev/submit_post
> 25 sp送信時のux改善

- public/styles/components.css
`main`をsvhで計算することにより対応
#30 
https://sawa-communication-6qmmxz13wyw5.deno.dev/submit_post
> 30 iosブラウザの場合にフッターが見切れる

- library/id_create_db.js
- public/index.html
- server.deno.js
> server.deno.jsの更新

- library/post_add_db_sp.js
- public/submit_post/submitting.js
細かなバグ修正をおこないました。SPの投稿に関するものは重要ですからご確認ください。
> 33 投稿フォームの修正

- deno.lock
- library/id_create_db.js
- public/components/footer.html
- public/daily_result/index.html
- public/lib/footerLinkModifier.js
- public/lib/sessionChecker.js
- public/profile/index.html
- public/styles/components.css
- public/styles/submit_post.css
- public/styles/welcome.css
- public/submit_post/index.html
- public/welcome/accountManager.js
- public/welcome/index.html
- server.deno.js
- アカウント作成機能
- 非ログイン時にwelcomeへ転送
#34 
https://sawa-communication-next--34-welcome.deno.dev/submit_post
↑ submit_post?
> ✨ アカウント・強制遷移・フッター調整

- library/id_create_db.js
- library/post_add_db_sp.js
- public/index.html
- public/profile/index.html
- public/submit_post/submitting.js
新しくuserにキーが必要になりました。ご確認ください。
また、ローカルストレージに関する仕様は私実装しておりませんからお願いをいたします。
最後に、SPを送信する際に今後は何個目のコメントかを表す(spNO)がいらなくなりました。
> 38 spを投稿した際にkeyの衝突が起こらないようにする

- library/post_add_db_sp.js
サーバーが「"自身にSPを送信することはできません"」という文字列をクライアントに返します。
タイトルの通り
> 自身にSPを送信できないように修正

- library/id_create_db.js
- public/profile/index.html
- public/styles/profile.css
- server.deno.js
- プロフィールのカード追加
- get user エンドポイント
#39 
https://sawa-communication-next--39-sp.deno.dev/profile
> 39 プロフィールのsp表示改善

- deno.json
- library/post_location_save_db.js
- public/test_counting/post_location.js
- server.deno.js
・test_coutingディレクトリを作成し、index.html,post_location.jsを作成した
・/test_countingにアクセスすると15秒ごとにサーバーに位置情報を送信され、すでにある場合はアップデートされます。ない場合は新しく作成されます。
#21
> ✨ test_countingディレクトリで位置情報を送れるようにした

- library/id_create_db.js
- library/quest_completed.js
- public/quest/index.html
- server.deno.js
> 45 クエストを作成する

- library/post_add_db_sp.js
- public/quest/index.html
- public/submit_post/submitting.js
送った人のクエスト完了日時が更新されるようになりました。
spを送信するとクエストが完了するようになりました。
> SPを送るとクエスト完了になる

- public/profile/index.html
- public/styles/profile.css
プロフィールにグレード表示を追加(グレードは固定)
#56 
https://sawa-communication-next--56.deno.dev/
> ✨ グレード表示(固定)

- public/daily_result/daily_result.css
- public/daily_result/index.html
・開発当初に最初に作ったページだったので流石に雑すぎたのでまだいい感じに改修した
・/daily_resultにアクセス
> 👍 さすがに雑すぎたdaily_resultのフロントエンドを軽く改修した

- library/get_grade.js
- public/my_grade/index.html
- public/profile/index.html
- public/styles/profile.css
- server.deno.js
各ユーザのページに現在のグレードを表示
#61
https://sawa-communication-next-5tf0xr53j2fz.deno.dev/
> 👍 グレード機能結合

- library/get_time.js
- library/id_create_db.js
- library/post_add_db_sp.js
- library/quest_completed.js
- public/lib/sessionChecker.js
- public/quest/index.html
- public/submit_post/submitting.js
アカウントがないときは絶対にアカウント作成画面に飛ばします。
アカウントがあるがクエストが完了していないときはクエスト画面に飛ばされます。
> 64 アカウントがあるがクエストを完了していなければクエスト画面に飛ばす

- public/profile/index.html
- public/styles/profile.css
- public/styles/submit_post.css
- public/submit_post/index.html
- public/welcome/index.html
- ID入力制限を追加
- プロフィールの表示改善
#65 
https://sawa-communication-next--65-sp.deno.dev/
> 65 sp入力フォームの制限追加

- library/quest_completed.js
- public/lib/sessionChecker.js
- public/quest/index.html
4つの実装を行いました。
- チュートリアル未達成の場合のみ表示する場所を用意
- サーバーに保存されているクエスト達成時間が間違っている問題を修正
- クエストがやってくる間隔を調整する方法をコメントで説明
- サーバーにクエストが完了しているか問い合わせた際に逆の回答が返ってくる問題を修正
クエストの間隔調整方法
/public/lib/sessionChecker.js Line9
と
/library/quest_completed.js Line22
を確認
> 68 クエスト画面にアプリケーションの概要を乗せる

- public/profile/index.html
- public/styles/components.css
- public/submit_post/submitting.js
送信先のプロフィールであることを示すバナーを作成
#70 
https://sawa-communication-next-5zh8jge46p1y.deno.dev/
> ✨ 通知バナーの作成

- library/id_create_db.js
- public/lib/sessionChecker.js
- public/quest/index.html
- public/submit_post/submitting.js
- public/welcome/accountManager.js
アカウント作成の後にクエストが発生しない問題を修正。
それに伴ってSPを送信した際にチュートリアルモードを終了できるように変更
> 73 アカウント追加した際に初心者クエストにたどり着かない問題を修正

- public/components/header.html
- public/quest/index.html
- public/styles/components.css
- public/styles/quest.css
- クエストページの修正
- ヘッダーにクエストへアクセス可能なヘルプボタンを追加
#70 
https://sawa-communication-next--74-css.deno.dev/
> 👍 クエストページのCSSを追加、ヘッダーからアクセス可能に

- public/submit_post/index.html
タイトルの通り
読み込んだQRコードの値はIDの中に格納されます。
> SP送信画面でQRコード生成と読み取り

- library/distilled_user_within_24hour.js
- public/profile/index.html
- public/styles/components.css
- public/takedarn_test/index.html
- public/takedarn_test/submit.js
- public/test_counting/post_location.js
- server.deno.js
サーバから24時間以内に交流した人のJSONファイル全部を持ってくる機能を実装した
#49
> ✨ サーバから24時間以内に交流したユーザーを返す機能を実装した

- public/index.html
- public/lib/metaPlacer.js
- public/profile/index.html
- public/quest/index.html
- public/submit_post/index.html
- public/welcome/index.html
完成ページにheadタグを共通化するスクリプトを配置
#86 
https://sawa-communication--86-head.deno.dev/
> ✨ 共通ヘッドコンポーネントを設置

- public/profile/index.html
- public/shop/index.html
- public/sticker/index.html
- server.deno.js
その他
- 二つのページでクエストに飛ぶように修正
- サーバーのエンドポイントが何をするものなのか一か所に記述
> SPの削除ボタンを作成。

- public/styles/submit_post.css
- public/submit_post/index.html
QRコードの読み取り画面の見た目を変更
#100 
https://sawa-communication--100-spqr.deno.dev/
> 👍 QRコードのヴィジュアルを修正

- library/post_add_db_sp.js
- public/submit_post/submitting.js
- 問題が発生した場合にプロフィールへリダイレクト
- 存在しないIDへはエラーを返すように
#88 
https://sawa-communication--88-idsp.deno.dev/
> 🚑 存在しないIDへ送ることができる問題を修正

- library/post_delete_db_sp.js
- public/profile/index.html
削除ボタンとCSSの調整
#94 
https://sawa-communication-7rc4hfhrkgwc.deno.dev/
> ✨ 削除ボタンの整理とCSS

- .gitignore
> ✨ gitignore

- library/post_add_db_sp.js
- library/post_sticker_buy.js
- library/quest_completed.js
- public/quest/index.html
- public/shop/index.html
- server.deno.js
> 99 商店画面で所持sp数を表示できるようにする

- public/lib/sessionChecker.js
- public/quest/index.html
> 114 新規作成に関する重大な問題を修正

- library/distilled_user_within_24hour.js
- public/daily_result/index.html
- public/daily_result/submit.js
- server.deno.js
> 24時間以内に交流したすべての人を表示するように修正

- public/styles/submit_post.css
- public/submit_post/index.html
> SP送信画面に自身のIDを表示するように変更

- public/shop/index.html
- public/submit_post/index.html
- public/submit_post/submitting.js
- public/welcome/accountManager.js
- public/welcome/index.html
各所で自作のアラートを出力するようにしました。
https://sawa-communication--124-inputtextarea.deno.dev/
> 124 inputとtextareaの無入力問題回避

- public/lib/sessionChecker.js
- public/quest/index.html
クエリパラメータに?type=1でアクセスすると警告が出ます。
> クエストページにリダイレクトされたら、通知が表示される

- public/edit_banner/index.html
- public/lib/sessionChecker.js
- public/shop/index.html
- public/styles/root.css
- public/styles/shop.css
ステッカーの管理画面のCSSとJSを変更
ショップよりアクセス可能
#120
https://sawa-communication--120-cssjs.deno.dev/
> 120 ステッカー管理画面のcssとjs

- public/profile/index.html
- public/styles/profile.css
> プロフィールのQRコードとりあえず削除

- public/daily_result/index.html
- public/profile/index.html
- public/quest/index.html
- public/search_around_people/get_around_people_location.js
- public/search_around_people/post_location.js
- public/shop/index.html
- public/submit_post/index.html
以下のページで送信します
・profile
・submit_post
・quest
・shop
・search_around_user
・daily_result
5秒ごとに位置情報の送信をしているので注意
see #140 
上記に記載しているページにアクセスした状態でコンソールを見ると送信されているものが見れます
> 👍 どのページでも常に位置情報を裏で送信できるようにした

- public/welcome/index.html
以降の新規アカウントでカテゴリ名が日本語になるように修正
趣味にゲーム・屋外活動を追加
#137 
https://sawa-communication--137.deno.dev/
> ✨趣味ラベルと項目追加

- public/daily_result/daily_result.css
- public/styles/components.css
- public/styles/profile.css
- public/styles/quest.css
- public/styles/root.css
- public/styles/search_around_people.css
- public/styles/shop.css
- public/styles/submit_post.css
- public/styles/welcome.css
> 👍CSSのprefixを追加

- public/index.html
> 親ページの小さな修正、3行消しました

- public/welcome/index.html
「データ削除」ボタンを取り払いました
#92 
特にありません
> 👍 データ削除ボタンの取り払い

- public/profile/index.html
- public/quest/index.html
- public/styles/quest.css
- public/styles/root.css
- public/styles/search_around_people.css
- public/styles/shop.css
- public/styles/submit_post.css
- public/styles/welcome.css
他人のステッカー表示
グラデーション
デバッグボタン
の修正
#160
> 160 致命的なバグ修正
